# ***** IMPORTANT *****
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# URL settings
domain: "amajor.github.io"
url: "https://amajor.github.io"
baseurl: "/website-remote-work-afloat"

# Site settings
title: Remote Work Afloat
author:
  name: Tea & Tides Stories
  url: https://teaandtidesstories.com
  email: hello@remoteworkafloat.com
  address: 2222 W. Grand River Ave Ste A
  city: Okemos
  state: MI
  zip: 48864
  country: USA
description: >- # this means to ignore newlines
  Whether you're planning your transition, choosing the right internet setup, or figuring out how to balance work with adventure, Remote Work Afloat provides practical advice, gear recommendations, and real-world strategies to help you stay connected and productive on the water.
loop_life_academy_url: "https://looplifeacademy.com"
amazon_affiliate_disclosure: >- # this means to ignore newlines
  As an Amazon Associate, I earn commission from qualifying purchases.

# Theme settings
minima:
  hide_site_feed_link: true
  show_excerpts: true

# Set default layout types
defaults: 
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
exclude:
  - README.md
  - .jekyll-cache/
  - .obsidian/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
